apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: teamforge

type: Opaque

stringData:
  PORT: "8000"
  NODE_ENV: "production"

  MONGO_URI: CHANGE_ME

  ACCESS_TOKEN_SECRET: CHANGE_ME
  REFRESH_TOKEN_SECRET: CHANGE_ME
  ACCESS_TOKEN_EXPIRY: "15m"
  REFRESH_TOKEN_EXPIRY: "7d"

  CORS_ORIGIN: CHANGE_ME
  FRONTEND_URL: CHANGE_ME
  FORGOT_PASSWORD_REDIRECT_URL: CHANGE_ME

  RAZORPAY_KEY_ID: CHANGE_ME
  RAZORPAY_KEY_SECRET: CHANGE_ME

  CLOUDINARY_CLOUD_NAME: CHANGE_ME
  CLOUDINARY_API_KEY: CHANGE_ME
  CLOUDINARY_API_SECRET: CHANGE_ME
  CLOUDINARY_FOLDER: CHANGE_ME

  BREVO_SMTP_SERVER: CHANGE_ME
  BREVO_SMTP_PORT: CHANGE_ME
  BREVO_SMTP_USER: CHANGE_ME
  BREVO_SMTP_PASS: CHANGE_ME
  EMAIL_FROM: CHANGE_ME

  GOOGLE_CLIENT_ID: CHANGE_ME
  GOOGLE_CLIENT_SECRET: CHANGE_ME
  GOOGLE_OAUTH_REDIRECT_URI: CHANGE_ME