name: CloudShield CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CloudShield
        uses: actions/checkout@v4
        with:
          path: CloudShield

      - name: Checkout TeamForge
        uses: actions/checkout@v4
        with:
          repository: yash-redkar/TeamForge
          path: TeamForge

      - name: Verify workspace
        run: |
          pwd
          ls -la
          ls -la CloudShield
          ls -la TeamForge